//
//  MenuPresenter.swift
//  MainPizzaScreen
//
//  Created by Vlad Ralovich on 03.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuPresentationLogic
{
  func presentSomething(response: Menu.Something.Response)
}

class MenuPresenter: MenuPresentationLogic
{
  weak var viewController: MenuDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Menu.Something.Response)
  {
    let viewModel = Menu.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
